routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Route::get('/', array('as'=> 'admin.login', 'uses' => 'Auth\LoginController@login'));
Route::post('/', array('as'=> 'admin.login.post', 'uses' => 'Auth\LoginController@loginPost'));
Route::group(['middleware' => 'auth' ,'prefix' => 'admin'], function () {
	Route::get('home', array('as'=> 'admin.home', 'uses' => 'HomeController@index'));
	Route::get('logout', array('as'=> 'admin.logout', 'uses' => 'Auth\LoginController@logout'));

	Route::get('userUserRevoke/{id}', array('as'=> 'admin.users.revokeuser', 'uses' => 'UserController@revoke'));
	Route::post('userBan', array('as'=> 'admin.users.ban', 'uses' => 'UserController@ban'));

	Route::resource('users', 'UserController');
	Route::resource('admins', 'AdminsController');
	Route::resource('gym','GymController');
	Route::resource('sportcategories','SportsCatController');
	Route::resource('tagsports','TagsportsController');
	Route::resource('hashtags', 'HashtagController');
	Route::resource('events', 'EventController');
	Route::resource('musclesgroups', 'MusclesgroupsController');
	Route::resource('workouts', 'WorkoutsController');
	Route::resource('supplements', 'SupplementsController');
	Route::resource('language', 'LanguageController');
	
	Route::post('gym/gym-update', array('as'=> 'gym.gym-update', 'uses' => 'GymController@gymUpdate'));

	Route::get('errorManager', array('as'=> 'admin.errorManager', 'uses' => 'ContentManagerController@contentManager'));
	Route::post('getLanguageContent', array('as'=> 'admin.getLanguageContent', 'uses' => 'ContentManagerController@getLanguageContent'));
	Route::post('updateContent', array('as'=> 'admin.updateContent', 'uses' => 'ContentManagerController@updateContent'));

	Route::get('manage-images/{type}/{id}',['as'=>'manage.media','uses'=>'ManageImageController@index']);
	Route::post('manageMedia',['as'=>'manageMedia.store','uses'=>'ManageImageController@store']);
	Route::delete('manageMedia/{type}/{id}',['as'=>'manageMedia.destroy','uses'=>'ManageImageController@destroy']);
});

Route::get('get-token/{id}',function($id){
	$user = \App\User::find($id);
    $token =  $user->createToken('MyApp',['user'])->accessToken;
    dd($token);
});

app/Http/Controllers/AdminThemeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class AdminThemeController extends Controller
{
    public function index()
    {
    	return view('newTheme.default');
    }

}

resources/views/adminTheme/alert.blade.php
@if ($errors->any())
<script type="text/javascript">
	$.notify({
     icon: 'pe-7s-gift',
     message: "<strong>Error Alert</strong> <br> Please check the form below for errors"

    },{
        type: 'error',
        timer: 4000
    });
</script>
@endif

@if ($message = Session::get('success'))
<script type="text/javascript">
	$.notify({
     icon: 'pe-7s-gift',
     message: "<strong>Success Alert</strong> <br>"+'<?php echo $message; ?>'

    },{
        type: 'success',
        timer: 4000
    });
</script>
<?php Session::forget('success');?>
@endif


@if ($message = Session::get('error'))
<script type="text/javascript">
	$.notify({
     icon: 'pe-7s-gift',
     message: "<strong>Error Alert</strong><br/>"+"<?php echo $message; ?>"

    },{
        type: 'error',
        timer: 4000
    });
</script>

<?php Session::forget('error');?>
@endif

@if ($message = Session::get('warning'))
<script type="text/javascript">
	$.notify({
     icon: 'pe-7s-gift',
     message: "<strong>Warning Alert</strong> <br>"+'<?php echo $message; ?>'

    },{
        type: 'warning',
        timer: 4000
    });
</script>
<?php Session::forget('warning');?>
@endif

@if ($message = Session::get('info'))
<script type="text/javascript">
	$.notify({
     icon: 'pe-7s-gift',
     message: "<strong>Information Alert</strong> <br>"+'<?php echo $message; ?>'

    },{
        type: 'info',
        timer: 4000
    });
</script>
<?php Session::forget('info');?>
@endif

resources/views/adminTheme/default.blade.php
<!doctype html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<link rel="icon" type="image/png" href="assets/img/favicon.ico">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />

	<title>Light Bootstrap Dashboard by Creative Tim</title>

	<meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />
    <meta name="viewport" content="width=device-width" />


    <!-- Bootstrap core CSS     -->
    <link href="{{ asset('adminTheme/css/bootstrap.min.css') }}" rel="stylesheet" />

    <!-- Animation library for notifications   -->
    <link href="{{ asset('adminTheme/css/animate.min.css') }}" rel="stylesheet"/>

    <!--  Light Bootstrap Table core CSS    -->
    <link href="{{ asset('adminTheme/css/light-bootstrap-dashboard.css')}}" rel="stylesheet"/>

    <!--  CSS for Demo Purpose, don't include it in your project     -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.5.0/css/bootstrap-datepicker.css" rel="stylesheet">

    <!--  CSS for Demo Purpose, don't include it in your project     -->
    <link href="{{ asset('adminTheme/css/demo.css')}}" rel="stylesheet" />


    <!--     Fonts and icons     -->
    <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
    <link href='http://fonts.googleapis.com/css?family=Roboto:400,700,300' rel='stylesheet' type='text/css'>
    <link href="{{ asset('adminTheme/css/pe-icon-7-stroke.css')}}" rel="stylesheet" />
    <link href="{{ asset('adminTheme/css/custom.css')}}" rel="stylesheet" />


     <!--   Core JS Files   -->
    <script src="{{ asset('adminTheme/js/jquery-1.10.2.js')}}" type="text/javascript"></script>

    <style type="text/css">
        #process_img{
            opacity: 0.7;
            position: fixed;
            text-align: center;
            top: 0;
            width: 80%;
            z-index: 1001;
            display: none;
            background: white;
            height: 100%;
        }
        #process_img img{
            position: relative;
            top: 40%;
        }
    </style>

    <script type="text/javascript">
        var current_page_url = "<?php echo URL::current(); ?>";
        var current_page_fullurl = "<?php echo URL::full(); ?>";
    </script>

    <script src="{{ asset('adminTheme/js/bootstrap.min.js')}}" type="text/javascript"></script>

    <!--  Checkbox, Radio & Switch Plugins -->
    <script src="{{ asset('adminTheme/js/bootstrap-checkbox-radio-switch.js')}}"></script>

    <!--  Charts Plugin -->
    <script src="{{ asset('adminTheme/js/chartist.min.js')}}"></script>

    <!--  Notifications Plugin    -->
    <script src="{{ asset('adminTheme/js/bootstrap-notify.js')}}"></script>

    <!--  Google Maps Plugin    -->
    <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?sensor=false"></script>

    <!-- Light Bootstrap Table Core javascript and methods for Demo purpose -->
    <script src="{{ asset('adminTheme/js/light-bootstrap-dashboard.js')}}"></script>
    <script src="{{ asset('adminTheme/js/bootbox.js') }}"></script>
    <script src="{{ asset('adminTheme/js/jquery.form.min.js') }}"></script>

    

</head>
<body>

<div class="wrapper">
    @include('adminTheme.sidebar')

    <div class="main-panel">

        @include('adminTheme.navbar')

        <div class="content" style="padding: 0px;">
            
            @yield('content')
        </div>

        @include('adminTheme.footer')

    </div>
</div>

<div id="process_img" style="display: none;">
    <img src="/adminTheme/img/loading.gif"/>
</div>

@include('adminTheme.alert')

    <!-- Light Bootstrap Table DEMO methods, don't include it in your project! -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.5.0/js/bootstrap-datepicker.js"></script>
    <script src="{{ asset('adminTheme/js/demo.js')}}"></script>
    <script src="{{ asset('adminTheme/js/crud.js')}}"></script>

    <script type="text/javascript">
        $(document).ready(function(){

            // demo.initChartist();

            // $.notify({
         //     icon: 'pe-7s-gift',
         //     message: "Welcome to <b>Light Bootstrap Dashboard</b> - a beautiful freebie for every web developer."

         //    },{
         //        type: 'info',
         //        timer: 4000
         //    });

        });
    </script>

    @yield('content')

</body>

</html>

resources/views/adminTheme/footer.blade.php
<footer class="footer">
    <div class="container-fluid">
        <nav class="pull-left">
            <ul>
                <li>
                    <a href="#">
                        Home
                    </a>
                </li>
                <li>
                    <a href="#">
                        Company
                    </a>
                </li>
                <li>
                    <a href="#">
                        Portfolio
                    </a>
                </li>
                <li>
                    <a href="#">
                       Blog
                    </a>
                </li>
            </ul>
        </nav>
        <p class="copyright pull-right">
            &copy; <script>document.write(new Date().getFullYear())</script> <a href="http://www.creative-tim.com">Creative Tim</a>, made with love for a better web
        </p>
    </div>
</footer>

resources/views/adminTheme/login.blade.php
<!DOCTYPE html>
<html>
<head>
  <title>{{ $projectTitle }}</title>
  <link rel="stylesheet" type="text/css" href="{{ asset('adminTheme/css/bootstrap.min.css') }}">
  
  <style type="text/css">
    @import url('https://fonts.googleapis.com/css?family=Nunito');
@import url('https://fonts.googleapis.com/css?family=Poiret+One');

body, html {
  height: 100%;
  background-repeat: no-repeat;    /*background-image: linear-gradient(rgb(12, 97, 33),rgb(104, 145, 162));*/
  background:black;
  position: relative;
}
#login-box {
  margin-top: 150px !important;
  position: absolute;
  top: 0px;
  left: 50%;
  transform: translateX(-50%);
  width: 350px;
  margin: 0 auto;
  border: 1px solid black;
  background: rgba(48, 46, 45, 1);
  min-height: 250px;
  padding: 20px;
  z-index: 9999;
}
#login-box .logo .logo-caption {
  font-family: 'Poiret One', cursive;
  color: white;
  text-align: center;
  margin-bottom: 0px;
}
#login-box .logo .tweak {
  color: #ff5252;
}
#login-box .controls {
  padding-top: 30px;
}
.logo-text{
  font-family: 'Poiret One', cursive;
  margin: 0px;
  color: #fff;
  text-align: center;
  margin-top: 100px;
}
#login-box .controls input {
  border-radius: 0px;
  background: rgb(98, 96, 96);
  border: 0px;
  color: white;
  font-family: 'Nunito', sans-serif;
}
.email ,.password{
  font-family: 'Nunito', sans-serif;
  color: #fff;
}
#login-box .controls input:focus {
  box-shadow: none;
}
#login-box .controls input:first-child {
  border-top-left-radius: 2px;
  border-top-right-radius: 2px;
}
#login-box .controls input:last-child {
  border-bottom-left-radius: 2px;
  border-bottom-right-radius: 2px;
}
#login-box button.btn-custom {
  border-radius: 2px;
  margin-top: 8px;
  background:#ff5252;
  border-color: rgba(48, 46, 45, 1);
  color: white;
  font-family: 'Nunito', sans-serif;
}
#login-box button.btn-custom:hover{
  -webkit-transition: all 500ms ease;
  -moz-transition: all 500ms ease;
  -ms-transition: all 500ms ease;
  -o-transition: all 500ms ease;
  transition: all 500ms ease;
  background: rgba(48, 46, 45, 1);
  border-color: #ff5252;
}
#particles-js{
    width: 100%;
    height: 100%;
    background-size: cover;
    background-position: 50% 50%;
    position: fixed;
    top: 0px;
    z-index:1;
}

.logo img{
  /* height:100%; */
  /* width: 100%;  */
}
  </style>

</head>
<body>
  <div class="container">
  @yield('content')
</div><!-- /.container -->
<div id="particles-js"></div>
</body>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/particles.js/2.0.0/particles.min.js"></script>
<script src="{{asset('newTheme/bower_components/jquery/dist/jquery.min.js')}}"></script>
<script type="text/javascript">
  $.getScript("https://cdnjs.cloudflare.com/ajax/libs/particles.js/2.0.0/particles.min.js", function(){
    particlesJS('particles-js',
      {
        "particles": {
          "number": {
            "value": 80,
            "density": {
              "enable": true,
              "value_area": 800
            }
          },
          "color": {
            "value": "#ffffff"
          },
          "shape": {
            "type": "circle",
            "stroke": {
              "width": 0,
              "color": "#000000"
            },
            "polygon": {
              "nb_sides": 5
            },
            "image": {
              "width": 100,
              "height": 100
            }
          },
          "opacity": {
            "value": 0.5,
            "random": false,
            "anim": {
              "enable": false,
              "speed": 1,
              "opacity_min": 0.1,
              "sync": false
            }
          },
          "size": {
            "value": 5,
            "random": true,
            "anim": {
              "enable": false,
              "speed": 40,
              "size_min": 0.1,
              "sync": false
            }
          },
          "line_linked": {
            "enable": true,
            "distance": 150,
            "color": "#ffffff",
            "opacity": 0.4,
            "width": 1
          },
          "move": {
            "enable": true,
            "speed": 6,
            "direction": "none",
            "random": false,
            "straight": false,
            "out_mode": "out",
            "attract": {
              "enable": false,
              "rotateX": 600,
              "rotateY": 1200
            }
          }
        },
        "interactivity": {
          "detect_on": "canvas",
          "events": {
            "onhover": {
              "enable": true,
              "mode": "repulse"
            },
            "onclick": {
              "enable": true,
              "mode": "push"
            },
            "resize": true
          },
          "modes": {
            "grab": {
              "distance": 400,
              "line_linked": {
                "opacity": 1
              }
            },
            "bubble": {
              "distance": 400,
              "size": 40,
              "duration": 2,
              "opacity": 8,
              "speed": 3
            },
            "repulse": {
              "distance": 200
            },
            "push": {
              "particles_nb": 4
            },
            "remove": {
              "particles_nb": 2
            }
          }
        },
        "retina_detect": true,
        "config_demo": {
          "hide_card": false,
          "background_color": "#b61924",
          "background_image": "",
          "background_position": "50% 50%",
          "background_repeat": "no-repeat",
          "background_size": "cover"
        }
      }
    );

});






</script>
</html>

resources/views/adminTheme/navbar.blade.php
<nav class="navbar navbar-default navbar-fixed">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navigation-example-2">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">Dashboard</a>
        </div>
        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav navbar-left">
                <li>
                    <a href="{{ route('admin.home') }}" class="dropdown-toggle" data-toggle="dropdown">
                        <i class="fa fa-dashboard"></i>
						<p class="hidden-lg hidden-md">Dashboard</p>
                    </a>
                </li>
            </ul>

            <ul class="nav navbar-nav navbar-right">
                <li>
                   <a href="">
                       <p>Hi, <strong>{{ auth()->user()->fullname }}</strong></p>
                    </a>
                </li>
				<li class="separator hidden-lg hidden-md"></li>
            </ul>
        </div>
    </div>
</nav>

resources/views/adminTheme/sidebar.blade.php
<?php 
    $currentPageURL = URL::current(); 
    $pageArray = explode('/', $currentPageURL);
    $pageActive = isset($pageArray[4]) ? $pageArray[4] : 'test';
?>

<div class="sidebar" data-color="purple" data-image="/adminTheme/img/sidebar-5.jpg">
	<div class="sidebar-wrapper">
        <div class="logo">
            <a href="http://www.creative-tim.com" class="simple-text">
                {{ $projectTitle }}
            </a>
        </div>

        <ul class="nav">
            <li class="{{ $pageActive == 'home' ? 'active' : ''  }}">
                <a href="{{ route('admin.home') }}">
                    <i class="pe-7s-graph"></i>
                    <p>Dashboard</p>
                </a>
            </li>
            <li class="{{ $pageActive == 'admins' ? 'active' : ''  }}">
                <a href="{{ route('admins.index') }}">
                    <i class="pe-7s-user"></i>
                    <p>Manage Admins</p>
                </a>
            </li>
            <li class="{{ $pageActive == 'users' ? 'active' : ''  }}">
                <a href="{{ route('users.index') }}">
                    <i class="pe-7s-user"></i>
                    <p>Manage Users</p>
                </a>
            </li>
            <li class="{{ $pageActive == 'hashtags' ? 'active' : ''  }}">
                <a href="{{ route('hashtags.index') }}">
                    <i class="pe-7s-science"></i>
                    <p>Manage Hashtags</p>
                </a>
            </li>
            <li class="{{ $pageActive == 'events' ? 'active' : ''  }}">
                <a href="{{ route('events.index') }}">
                    <i class="pe-7s-science"></i>
                    <p>Manage Events</p>
                </a>
            </li>
            <li class="active-pro">
                <a href="{{ route('admin.logout') }}">
                    <i class="pe-7s-rocket"></i>
                    <p>Logout</p>
                </a>
            </li>
        </ul>
	</div>
</div>